import {
  Home,
  PackageOpen,
  ClipboardList,
  Wallet,
  Database,
  Star,
  History,
  User,
  Settings,
  RefreshCcw,
  Search,
  Filter,
  X,
  ChevronDown,
  SlidersHorizontal,
  Layers,
  List,
  Calendar,
  Clock,
  AlertCircle,
  Check,
  Download,
  Upload,
  Trash,
  Plus,
  MoreVertical,
  Moon,
  Sun,
  Laptop
} from "lucide-react";

export const Icons = {
  home: Home,
  packageOpen: PackageOpen,
  clipboardList: ClipboardList,
  wallet: Wallet,
  database: Database,
  star: Star,
  history: History,
  user: User,
  settings: Settings,
  refresh: RefreshCcw,
  search: Search,
  filter: Filter,
  close: X,
  chevronDown: ChevronDown,
  sliders: SlidersHorizontal,
  layers: Layers,
  list: List,
  calendar: Calendar,
  clock: Clock,
  alert: AlertCircle,
  check: Check,
  download: Download,
  upload: Upload,
  trash: Trash,
  add: Plus,
  more: MoreVertical,
  moon: Moon,
  sun: Sun,
  system: Laptop
};